apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # Port exposed to the external world
      targetPort: 80  # Port the container is listening on
      nodePort: 30001  # The port on your local machine (you can change this to any available port)
  type: NodePort  # Expose the service via NodePort for local access
